version: '3.1'
# service
services:
    node:
        image: node:12
        tty: true
        volumes: 
            - ./:/app:cached
        working_dir: /app
        ports:
            - 3000:3000
        environment: 
            HOST: 0.0.0.0
